- hosts: localhost
  tasks:
    - name: Upgrade all packages
      become: yes
      yum: name=* state=latest

    - name: Remove Rhythmbox
      become: yes
      package:
        name: rhythmbox
        state: absent